name: Integration tests
on: [push, pull_request]
jobs:
  test:
    name: Run Tox
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        make install
    - name: Run tox
      run: tox
